 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bocas", type: :request do
  # Boca. As you add validations to Boca, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Boca.create! valid_attributes
      get bocas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      boca = Boca.create! valid_attributes
      get boca_url(boca)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_boca_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      boca = Boca.create! valid_attributes
      get edit_boca_url(boca)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Boca" do
        expect {
          post bocas_url, params: { boca: valid_attributes }
        }.to change(Boca, :count).by(1)
      end

      it "redirects to the created boca" do
        post bocas_url, params: { boca: valid_attributes }
        expect(response).to redirect_to(boca_url(Boca.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Boca" do
        expect {
          post bocas_url, params: { boca: invalid_attributes }
        }.to change(Boca, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bocas_url, params: { boca: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested boca" do
        boca = Boca.create! valid_attributes
        patch boca_url(boca), params: { boca: new_attributes }
        boca.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the boca" do
        boca = Boca.create! valid_attributes
        patch boca_url(boca), params: { boca: new_attributes }
        boca.reload
        expect(response).to redirect_to(boca_url(boca))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        boca = Boca.create! valid_attributes
        patch boca_url(boca), params: { boca: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested boca" do
      boca = Boca.create! valid_attributes
      expect {
        delete boca_url(boca)
      }.to change(Boca, :count).by(-1)
    end

    it "redirects to the bocas list" do
      boca = Boca.create! valid_attributes
      delete boca_url(boca)
      expect(response).to redirect_to(bocas_url)
    end
  end
end
