 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/categoria", type: :request do
  # Categorium. As you add validations to Categorium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Categorium.create! valid_attributes
      get categoria_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      categorium = Categorium.create! valid_attributes
      get categorium_url(categorium)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_categorium_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      categorium = Categorium.create! valid_attributes
      get edit_categorium_url(categorium)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Categorium" do
        expect {
          post categoria_url, params: { categorium: valid_attributes }
        }.to change(Categorium, :count).by(1)
      end

      it "redirects to the created categorium" do
        post categoria_url, params: { categorium: valid_attributes }
        expect(response).to redirect_to(categorium_url(Categorium.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Categorium" do
        expect {
          post categoria_url, params: { categorium: invalid_attributes }
        }.to change(Categorium, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post categoria_url, params: { categorium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested categorium" do
        categorium = Categorium.create! valid_attributes
        patch categorium_url(categorium), params: { categorium: new_attributes }
        categorium.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the categorium" do
        categorium = Categorium.create! valid_attributes
        patch categorium_url(categorium), params: { categorium: new_attributes }
        categorium.reload
        expect(response).to redirect_to(categorium_url(categorium))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        categorium = Categorium.create! valid_attributes
        patch categorium_url(categorium), params: { categorium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested categorium" do
      categorium = Categorium.create! valid_attributes
      expect {
        delete categorium_url(categorium)
      }.to change(Categorium, :count).by(-1)
    end

    it "redirects to the categoria list" do
      categorium = Categorium.create! valid_attributes
      delete categorium_url(categorium)
      expect(response).to redirect_to(categoria_url)
    end
  end
end
