 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/consulta", type: :request do
  # Consultum. As you add validations to Consultum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Consultum.create! valid_attributes
      get consulta_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      consultum = Consultum.create! valid_attributes
      get consultum_url(consultum)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_consultum_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      consultum = Consultum.create! valid_attributes
      get edit_consultum_url(consultum)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Consultum" do
        expect {
          post consulta_url, params: { consultum: valid_attributes }
        }.to change(Consultum, :count).by(1)
      end

      it "redirects to the created consultum" do
        post consulta_url, params: { consultum: valid_attributes }
        expect(response).to redirect_to(consultum_url(Consultum.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Consultum" do
        expect {
          post consulta_url, params: { consultum: invalid_attributes }
        }.to change(Consultum, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post consulta_url, params: { consultum: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested consultum" do
        consultum = Consultum.create! valid_attributes
        patch consultum_url(consultum), params: { consultum: new_attributes }
        consultum.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the consultum" do
        consultum = Consultum.create! valid_attributes
        patch consultum_url(consultum), params: { consultum: new_attributes }
        consultum.reload
        expect(response).to redirect_to(consultum_url(consultum))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        consultum = Consultum.create! valid_attributes
        patch consultum_url(consultum), params: { consultum: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested consultum" do
      consultum = Consultum.create! valid_attributes
      expect {
        delete consultum_url(consultum)
      }.to change(Consultum, :count).by(-1)
    end

    it "redirects to the consulta list" do
      consultum = Consultum.create! valid_attributes
      delete consultum_url(consultum)
      expect(response).to redirect_to(consulta_url)
    end
  end
end
