 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dentes", type: :request do
  # Dente. As you add validations to Dente, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Dente.create! valid_attributes
      get dentes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dente = Dente.create! valid_attributes
      get dente_url(dente)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dente_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      dente = Dente.create! valid_attributes
      get edit_dente_url(dente)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Dente" do
        expect {
          post dentes_url, params: { dente: valid_attributes }
        }.to change(Dente, :count).by(1)
      end

      it "redirects to the created dente" do
        post dentes_url, params: { dente: valid_attributes }
        expect(response).to redirect_to(dente_url(Dente.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Dente" do
        expect {
          post dentes_url, params: { dente: invalid_attributes }
        }.to change(Dente, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post dentes_url, params: { dente: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dente" do
        dente = Dente.create! valid_attributes
        patch dente_url(dente), params: { dente: new_attributes }
        dente.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dente" do
        dente = Dente.create! valid_attributes
        patch dente_url(dente), params: { dente: new_attributes }
        dente.reload
        expect(response).to redirect_to(dente_url(dente))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        dente = Dente.create! valid_attributes
        patch dente_url(dente), params: { dente: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dente" do
      dente = Dente.create! valid_attributes
      expect {
        delete dente_url(dente)
      }.to change(Dente, :count).by(-1)
    end

    it "redirects to the dentes list" do
      dente = Dente.create! valid_attributes
      delete dente_url(dente)
      expect(response).to redirect_to(dentes_url)
    end
  end
end
