 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/orcamentos", type: :request do
  # Orcamento. As you add validations to Orcamento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Orcamento.create! valid_attributes
      get orcamentos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      orcamento = Orcamento.create! valid_attributes
      get orcamento_url(orcamento)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_orcamento_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      orcamento = Orcamento.create! valid_attributes
      get edit_orcamento_url(orcamento)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Orcamento" do
        expect {
          post orcamentos_url, params: { orcamento: valid_attributes }
        }.to change(Orcamento, :count).by(1)
      end

      it "redirects to the created orcamento" do
        post orcamentos_url, params: { orcamento: valid_attributes }
        expect(response).to redirect_to(orcamento_url(Orcamento.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Orcamento" do
        expect {
          post orcamentos_url, params: { orcamento: invalid_attributes }
        }.to change(Orcamento, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post orcamentos_url, params: { orcamento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested orcamento" do
        orcamento = Orcamento.create! valid_attributes
        patch orcamento_url(orcamento), params: { orcamento: new_attributes }
        orcamento.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the orcamento" do
        orcamento = Orcamento.create! valid_attributes
        patch orcamento_url(orcamento), params: { orcamento: new_attributes }
        orcamento.reload
        expect(response).to redirect_to(orcamento_url(orcamento))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        orcamento = Orcamento.create! valid_attributes
        patch orcamento_url(orcamento), params: { orcamento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested orcamento" do
      orcamento = Orcamento.create! valid_attributes
      expect {
        delete orcamento_url(orcamento)
      }.to change(Orcamento, :count).by(-1)
    end

    it "redirects to the orcamentos list" do
      orcamento = Orcamento.create! valid_attributes
      delete orcamento_url(orcamento)
      expect(response).to redirect_to(orcamentos_url)
    end
  end
end
