 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/orcamento_details", type: :request do
  # OrcamentoDetail. As you add validations to OrcamentoDetail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OrcamentoDetail.create! valid_attributes
      get orcamento_details_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      orcamento_detail = OrcamentoDetail.create! valid_attributes
      get orcamento_detail_url(orcamento_detail)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_orcamento_detail_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      orcamento_detail = OrcamentoDetail.create! valid_attributes
      get edit_orcamento_detail_url(orcamento_detail)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OrcamentoDetail" do
        expect {
          post orcamento_details_url, params: { orcamento_detail: valid_attributes }
        }.to change(OrcamentoDetail, :count).by(1)
      end

      it "redirects to the created orcamento_detail" do
        post orcamento_details_url, params: { orcamento_detail: valid_attributes }
        expect(response).to redirect_to(orcamento_detail_url(OrcamentoDetail.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OrcamentoDetail" do
        expect {
          post orcamento_details_url, params: { orcamento_detail: invalid_attributes }
        }.to change(OrcamentoDetail, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post orcamento_details_url, params: { orcamento_detail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested orcamento_detail" do
        orcamento_detail = OrcamentoDetail.create! valid_attributes
        patch orcamento_detail_url(orcamento_detail), params: { orcamento_detail: new_attributes }
        orcamento_detail.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the orcamento_detail" do
        orcamento_detail = OrcamentoDetail.create! valid_attributes
        patch orcamento_detail_url(orcamento_detail), params: { orcamento_detail: new_attributes }
        orcamento_detail.reload
        expect(response).to redirect_to(orcamento_detail_url(orcamento_detail))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        orcamento_detail = OrcamentoDetail.create! valid_attributes
        patch orcamento_detail_url(orcamento_detail), params: { orcamento_detail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested orcamento_detail" do
      orcamento_detail = OrcamentoDetail.create! valid_attributes
      expect {
        delete orcamento_detail_url(orcamento_detail)
      }.to change(OrcamentoDetail, :count).by(-1)
    end

    it "redirects to the orcamento_details list" do
      orcamento_detail = OrcamentoDetail.create! valid_attributes
      delete orcamento_detail_url(orcamento_detail)
      expect(response).to redirect_to(orcamento_details_url)
    end
  end
end
