 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pagamentos", type: :request do
  # Pagamento. As you add validations to Pagamento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Pagamento.create! valid_attributes
      get pagamentos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pagamento = Pagamento.create! valid_attributes
      get pagamento_url(pagamento)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pagamento_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      pagamento = Pagamento.create! valid_attributes
      get edit_pagamento_url(pagamento)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Pagamento" do
        expect {
          post pagamentos_url, params: { pagamento: valid_attributes }
        }.to change(Pagamento, :count).by(1)
      end

      it "redirects to the created pagamento" do
        post pagamentos_url, params: { pagamento: valid_attributes }
        expect(response).to redirect_to(pagamento_url(Pagamento.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Pagamento" do
        expect {
          post pagamentos_url, params: { pagamento: invalid_attributes }
        }.to change(Pagamento, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pagamentos_url, params: { pagamento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pagamento" do
        pagamento = Pagamento.create! valid_attributes
        patch pagamento_url(pagamento), params: { pagamento: new_attributes }
        pagamento.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pagamento" do
        pagamento = Pagamento.create! valid_attributes
        patch pagamento_url(pagamento), params: { pagamento: new_attributes }
        pagamento.reload
        expect(response).to redirect_to(pagamento_url(pagamento))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pagamento = Pagamento.create! valid_attributes
        patch pagamento_url(pagamento), params: { pagamento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pagamento" do
      pagamento = Pagamento.create! valid_attributes
      expect {
        delete pagamento_url(pagamento)
      }.to change(Pagamento, :count).by(-1)
    end

    it "redirects to the pagamentos list" do
      pagamento = Pagamento.create! valid_attributes
      delete pagamento_url(pagamento)
      expect(response).to redirect_to(pagamentos_url)
    end
  end
end
