 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/produtos", type: :request do
  # Produto. As you add validations to Produto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Produto.create! valid_attributes
      get produtos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      produto = Produto.create! valid_attributes
      get produto_url(produto)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_produto_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      produto = Produto.create! valid_attributes
      get edit_produto_url(produto)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Produto" do
        expect {
          post produtos_url, params: { produto: valid_attributes }
        }.to change(Produto, :count).by(1)
      end

      it "redirects to the created produto" do
        post produtos_url, params: { produto: valid_attributes }
        expect(response).to redirect_to(produto_url(Produto.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Produto" do
        expect {
          post produtos_url, params: { produto: invalid_attributes }
        }.to change(Produto, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post produtos_url, params: { produto: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested produto" do
        produto = Produto.create! valid_attributes
        patch produto_url(produto), params: { produto: new_attributes }
        produto.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the produto" do
        produto = Produto.create! valid_attributes
        patch produto_url(produto), params: { produto: new_attributes }
        produto.reload
        expect(response).to redirect_to(produto_url(produto))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        produto = Produto.create! valid_attributes
        patch produto_url(produto), params: { produto: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested produto" do
      produto = Produto.create! valid_attributes
      expect {
        delete produto_url(produto)
      }.to change(Produto, :count).by(-1)
    end

    it "redirects to the produtos list" do
      produto = Produto.create! valid_attributes
      delete produto_url(produto)
      expect(response).to redirect_to(produtos_url)
    end
  end
end
