 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/servicos", type: :request do
  # Servico. As you add validations to Servico, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Servico.create! valid_attributes
      get servicos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      servico = Servico.create! valid_attributes
      get servico_url(servico)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_servico_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      servico = Servico.create! valid_attributes
      get edit_servico_url(servico)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Servico" do
        expect {
          post servicos_url, params: { servico: valid_attributes }
        }.to change(Servico, :count).by(1)
      end

      it "redirects to the created servico" do
        post servicos_url, params: { servico: valid_attributes }
        expect(response).to redirect_to(servico_url(Servico.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Servico" do
        expect {
          post servicos_url, params: { servico: invalid_attributes }
        }.to change(Servico, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post servicos_url, params: { servico: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested servico" do
        servico = Servico.create! valid_attributes
        patch servico_url(servico), params: { servico: new_attributes }
        servico.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the servico" do
        servico = Servico.create! valid_attributes
        patch servico_url(servico), params: { servico: new_attributes }
        servico.reload
        expect(response).to redirect_to(servico_url(servico))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        servico = Servico.create! valid_attributes
        patch servico_url(servico), params: { servico: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested servico" do
      servico = Servico.create! valid_attributes
      expect {
        delete servico_url(servico)
      }.to change(Servico, :count).by(-1)
    end

    it "redirects to the servicos list" do
      servico = Servico.create! valid_attributes
      delete servico_url(servico)
      expect(response).to redirect_to(servicos_url)
    end
  end
end
