 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tratamentos", type: :request do
  # Tratamento. As you add validations to Tratamento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Tratamento.create! valid_attributes
      get tratamentos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tratamento = Tratamento.create! valid_attributes
      get tratamento_url(tratamento)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tratamento_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tratamento = Tratamento.create! valid_attributes
      get edit_tratamento_url(tratamento)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tratamento" do
        expect {
          post tratamentos_url, params: { tratamento: valid_attributes }
        }.to change(Tratamento, :count).by(1)
      end

      it "redirects to the created tratamento" do
        post tratamentos_url, params: { tratamento: valid_attributes }
        expect(response).to redirect_to(tratamento_url(Tratamento.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tratamento" do
        expect {
          post tratamentos_url, params: { tratamento: invalid_attributes }
        }.to change(Tratamento, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tratamentos_url, params: { tratamento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tratamento" do
        tratamento = Tratamento.create! valid_attributes
        patch tratamento_url(tratamento), params: { tratamento: new_attributes }
        tratamento.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tratamento" do
        tratamento = Tratamento.create! valid_attributes
        patch tratamento_url(tratamento), params: { tratamento: new_attributes }
        tratamento.reload
        expect(response).to redirect_to(tratamento_url(tratamento))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tratamento = Tratamento.create! valid_attributes
        patch tratamento_url(tratamento), params: { tratamento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tratamento" do
      tratamento = Tratamento.create! valid_attributes
      expect {
        delete tratamento_url(tratamento)
      }.to change(Tratamento, :count).by(-1)
    end

    it "redirects to the tratamentos list" do
      tratamento = Tratamento.create! valid_attributes
      delete tratamento_url(tratamento)
      expect(response).to redirect_to(tratamentos_url)
    end
  end
end
